### ISSUE TITLE
[1.17] Oak Leaves Bug

### ISSUE THREAD

**Issue by Khytwel** [teamauroramods/Fruitful-Fabric#3]
When you break an Oak Leaves with your hand, you get the block.

**Comment by AlisterGontineac** [comment]
Ah yeah I was literally just coming to report this. 

It took me two days to narrow down.

When breaking leaves of any kind, with hands or any tool this mod forces the leaf block to drop instead effectively turning off decay function.

It is super annoying when you have instant leaf decay on, and the next thing you know your inventory is filled with leaf blocks, and you get no sticks, saplings or apples.

**Comment by yavincl** [comment]
Can confirm.

**Comment by SaltSouls** [comment]
This happens when using tree chopping mods as well.

**Comment by Khytwel** [comment]
No, this happens without any other mods besides Fruitful.

**Comment by SaltSouls** [comment]
> No, this happens without any other mods besides Fruitful.

I know, that's why I stated "as well". Just to clarify that this problem persists even when combined with other mods and isn't just limited to a single action break. I assume the problem is that the loot table for leaves got messed up and as a result they are now dropping the block, even though they shouldn't be.

**Comment by Angular-Angel** [comment]
Can confirm, I also have this problem. :/

**Comment by f-raZ0R** [comment]
can confirm the lack of a fix

**Comment by EbonyDream** [comment]
Can confirm that I also have this issue. The files on the Curse Forge page hasn't even been updated since June.

**Comment by AlisterGontineac** [comment]
Meh, moving away from this mod >_>

**Comment by Mattabase** [comment]
A quick work around is to remove the files located inside the jar of the mod at the below location. 

fruitful-1.0.0.jar\data\minecraft\loot_tables\blocks\

**Comment by ShockMicro** [comment]
I apologize for how slow it took to fix this issue, I thought I had already pushed a fix to this once and so I completely forgot about the issue. Just a simple mistake in porting the mod to 1.17, hopefully shouldn't happen again.
