### ISSUE TITLE
Don't nest cloth config.

### ISSUE THREAD

**Issue by K0-RR** [teamauroramods/Fruitful-Fabric#8]
This lib is highly popular and its size is huge. It gets included in many mods so the modpack with 80 mods is 40 MB bigger in size than needed.

**Comment by Steven-Baez** [comment]
It's just for the convenience of the user so they don't have to download it anyways, I'll try of finding a better config system of just nest the lite version but for now, I have to close this sorry, hopefully, I can find a way to have a better config system.
